#!/bin/bash
# Mapping sequencing data to hg38 with bowtie2, followed by transforming sam file to bam file, removing duplicate and indexing bam file with samtools. For more information, please refer to bowtie2 and samtools mannual.
#$ -cwd
#$ -v PATH,LD_LIBRARY_PATH,CLASSPATH
#$ -l m_mem_free=10G
#$ -l tmp_free=50G
for i in *R1*val_1*.fq.gz
do
   echo $i
   R2=${i/R1_001_ME_val_1/R2_001_ME_val_2}
   echo $R2
   name=${i%%_R1*}
   echo $name
   bowtie2 --very-sensitive-local --no-unal --no-mixed  --phred33 -I 10 -X 700 --no-discordant -p 16 -x /grid/mills/home/xsun/index_file/hg38/hg38_genome/hg38 --un-conc ${name}_bt2_unmapped -1 $i -2 $R2 -S ${name}_bt2_snstv.sam
   samtools view -bS  ${name}_bt2_snstv.sam > ${name}_bt2_snstv.bam
   samtools sort ${name}_bt2_snstv.bam -o ${name}_bt2_snstv.sorted.bam
   rm ${name}_bt2_snstv.bam
   samtools rmdup -s ${name}_bt2_snstv.sorted.bam ${name}_bt2_snstv.sorted.rd.bam
   samtools index ${name}_bt2_snstv.sorted.rd.bam
   rm ${name}_bt2_snstv.sorted.bam
done
exit 0
